name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Ensure Requirements file is installed
        run: |
          pip install -r requirements.txt
        working-directory: 'UI Automation'

      - name: Install Playwright Browsers
        run: |
          playwright install
        working-directory: 'UI Automation'

      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps
        working-directory: 'UI Automation'

      - name: Run tests
        run: |
          xvfb-run pytest testcases
        working-directory: 'UI Automation'
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      
      #- name: Upload Allure Report
       # uses: actions/upload-artifact@v3
        #with:
         # name: allure-report
          #path: UI Automation/allure-report

      #- name: Generate Allure Report
       # run: |
        #  allure generate allure-report --clean -o allure-report
        #working-directory: 'UI Automation'

      #- name: Upload Allure HTML Report
        #uses: actions/upload-artifact@v3
        #with:
          #name: allure-html-report
          #path: UI Automation/allure-report
          